### ISSUE TITLE
404 errors due to move to src directory

### ISSUE THREAD

**Issue by mauritsvanrees** [collective/collective.mailchimp#21]
I mentioned this in a comment in pull request #20, but an issue would have been clearer.

When I now visit the `@@newsletter` page, I get a 404 NotFound.

There is a warning: OFS.Uninstalled Could not import class 'ICollectiveMailchimp' from module 'collective.mailchimp.interfaces'

When I enable NotFound on the error_log, I get various errors, `Cannot locate object at: http://localhost:8080/Plone/@@newsletter`, same for `++resource++collective.mailchimp.images`, etcetera. The add-ons control panel no longer lists MailChimp as installed, nor as installable.

Core issue is probably because the browser layer is not found.

**Comment by tisto** [comment]
It seems you have to re-install collective.mailchimp to fix this. We could either undo the pull request and re-release or create an upgrade step.

**Comment by mauritsvanrees** [comment]
If you undo the directory move, then for people that have installed 2.0 already, an upgrade step would still be needed. So it may be better to only create the upgrade step.

**Comment by tisto** [comment]
Right. I'm already working on the upgrade step...

**Comment by tisto** [comment]
Fixed: https://github.com/collective/collective.mailchimp/pull/22

**Comment by mauritsvanrees** [comment]
That helps, thanks.

I now see that it was far more broken locally for me due to one simple reason: I did not run bin/buildout after you moved the code to the src directory. This meant that my local egg-info was wrong and no mailchimp code could be found. This is also the reason why mailchimp did not even show up anymore in my add-ons control panel. After running bin/buildout, most stuff functioned again. Only the css and images could not be loaded, which is fixed with your upgrade step.

I was already wondering why you did not notice yourself that the src move left the package utterly broken, but it was not broken, it just needed a bin/buildout run. :-)

Incidentally, the collective/mailchimp dir was still in place in my checkout. Git did not remove it, because it contained `.pyc` and `.mo` files. I would actually now expect that it had continued working because those compiles python files were there. Ah, but the zcml files were not in those directories, so that's why it did not work anymore.

Mystery solved. :-)
