### ISSUE TITLE
Missing files in 2.0 and 2.0.1

### ISSUE THREAD

**Issue by mauritsvanrees** [collective/collective.mailchimp#23]
The non Python files are missing. The `MANIFEST.in` still tried to include `collective` instead of `src`. I have fixed this file in fbb140b8d4580c7d9c938c95746d93702dd2e159.

@tisto Can you make a new release?

For the bus factor: can you add another person on PyPI? My PyPI id is maurits.

**Comment by tisto** [comment]
@mauritsvanrees you have release permissions on pypi.

**Comment by mauritsvanrees** [comment]
Thanks. I have released 2.0.2 and confirm it works.
