### ISSUE TITLE
can't change a bad or invalidated API key

### ISSUE THREAD

**Issue by tkimnguyen** [collective/collective.mailchimp#26]
collective.mailchimp = 2.0.2
Plone 5.0.4 Unified Installer on Mac OS Sierra 10.12 Beta

I'd set an API key value that worked but someone else deleted the Mailchimp account, invalidating the API key value I'd provided. Going to http://localhost:8080/Plone/@@mailchimp-settings now gives 

```
Traceback (innermost last):
  Module ZPublisher.Publish, line 138, in publish
  Module ZPublisher.mapply, line 77, in mapply
  Module ZPublisher.Publish, line 48, in call_object
  Module plone.z3cform.layout, line 66, in __call__
  Module plone.z3cform.layout, line 50, in update
  Module collective.mailchimp.browser.controlpanel, line 31, in update
  Module collective.mailchimp.browser.controlpanel, line 42, in updateCache
  Module collective.mailchimp.locator, line 264, in updateCache
  Module collective.mailchimp.locator, line 136, in _lists
  Module collective.mailchimp.locator, line 119, in api_request
  Module collective.mailchimp.locator, line 82, in _deserialize_response
  Module collective.mailchimp.locator, line 99, in _fail_if_mailchimp_exc
MailChimpException: MailChimp error code 401: "Your API key may be invalid, or you've attempted to access the wrong datacenter."
None
```

so I seem to be unable to change that API key value.

Deleting and re-creating the /Plone site didn't help... still can't view the control panel.

When I restarted my Plone instance I was able to view the control panel. Something is being cached?

**Comment by tisto** [comment]
Yeah. I ran into this as well. We should really fix this. Hard to find time though...pr's are welcome. ;)

**Comment by mauritsvanrees** [comment]
I have a PR to fix this: https://github.com/collective/collective.mailchimp/pull/65
