### ISSUE TITLE
missing English translations?

### ISSUE THREAD

**Issue by tkimnguyen** [collective/collective.mailchimp#27]
The field IDs are being shown in the control panel... presumably we need an en/LC_MESSAGES :) 

![image](https://cloud.githubusercontent.com/assets/815418/18143191/a2ae0ca6-6f86-11e6-9d8c-cba40f285e3c.png)

**Comment by tisto** [comment]
@tkimnguyen yep. Wanna provide one? :)

**Comment by tkimnguyen** [comment]
aw man :)

**Comment by agitator** [comment]
defaults were missing - fixed in https://github.com/collective/collective.mailchimp/pull/57
