### ISSUE TITLE
clarify collective.mailchimp's purpose in the README

### ISSUE THREAD

**Issue by tkimnguyen** [collective/collective.mailchimp#29]
I _think_ I understand that this add-on lets you display a portlet to let website visitors subscribe to one or more Mailchimp lists. (Does it do more than that?) It would be great to have that stated clearly at the top of the README.

**Comment by tisto** [comment]
@tkimnguyen thanks for the hint. I updated the README. Please let me know if you are happy with it. :)

**Comment by tkimnguyen** [comment]
Looks great @tisto thx!
