### ISSUE TITLE
Portlet: 'MailChimp error code -90: "You must specify a id value for the listSubscribe method"'

### ISSUE THREAD

**Issue by csenger** [collective/collective.mailchimp#3]
`.browser.newsletter.NewsletterSubscribeForm` uses 

* a list_id from the request or 
* the default list stored in the site wide mailchimp configuration. 

It does not use the list set in the portlet configuration, If both are missing it will not pass an list id to `IMailchimpLocator.subscribe()` and fail with `MailChimp error code -90: "You must specify a id value for the listSubscribe method"'`.

**Comment by mauritsvanrees** [comment]
We are using a newer api now, so I guess this can no longer happen, at least not in the same way.
Please reopen if you still see this with the latest collective.mailchimp (currently 2.0.2).
