### ISSUE TITLE
Add prefix and/or suffix rich text in portlet

### ISSUE THREAD

**Issue by ivanteoh** [collective/collective.mailchimp#30]
Hi @tisto,

One of our client like to add some rich text before and/or after the form in MailChimp portlet.

Will you accept if we pull request on this package? Or it is preferable to create a new package extends this package, based from https://github.com/collective/collective.mailchimp#extend-newsletter-subscription-form?

**Comment by tisto** [comment]
@ivanteoh any update on this? Otherwise I would close the issue...

**Comment by ivanteoh** [comment]
Hi @tisto, I will follow this with @djay and get back to you soon. Thanks for reminding me.

**Comment by tisto** [comment]
@ivanteoh any updates on this? I will close the issue due to inactivity. Feel free to re-open if you disagree.
