### ISSUE TITLE
Confirmation mail seems empty

### ISSUE THREAD

**Issue by mauritsvanrees** [collective/collective.mailchimp#52]
We have two sites with collective.mailchimp, one with 2.0.2, another with 2.2.2. When you use its registration form, you get a seemingly empty mail from MailChimp. In fact, if your mail client allows, you can switch to the plain text mime part en then it shows up fine. So only the html part is broken.

This mail is not sent by Plone, but by MailChimp.
But when you use the form on the MailChimp site itself, the confirmation mail is fine.
So using the api results in a bad mail.
We asked MailChimp support, but did not get a useful answer.

My main question is: are others seeing this too?

**Comment by tisto** [comment]
@mauritsvanrees we did not run into this problem as far as I know. cc @csenger
