### ISSUE TITLE
"Plone 6" takes validation more serious

### ISSUE THREAD

**Issue by agitator** [collective/collective.mailchimp#56]
<img width="671" alt="Screenshot 2021-01-19 at 10 24 31" src="https://user-images.githubusercontent.com/365761/105015191-925eea00-5a41-11eb-8287-ab9a284b16d0.png">
<img width="606" alt="Screenshot 2021-01-19 at 10 22 48" src="https://user-images.githubusercontent.com/365761/105015201-9428ad80-5a41-11eb-8640-e1235e7efdfb.png">

preparing fix

**Comment by agitator** [comment]
fix https://github.com/collective/collective.mailchimp/pull/57

**Comment by jensens** [comment]
`required=True` for a boolean does not make much sense anyway (except to agree service-terms and similar).
