### ISSUE TITLE
Make it possible to dynamically obtain the list of fields for the the form to be rendered

### ISSUE THREAD

**Issue by barseghyanartur** [collective/collective.mailchimp#7]
The best place (from user perspective) would be the portlet configuration screen, in which the admin would just select which fields should be included in the form (using checkboxes). It's not necessary to send a new API request when rendering a form; chosen fields could be stored locally and re-fetched only when the edit portlet screen is opened.

**Comment by tisto** [comment]
That would be a nice addition. Though, not trivial to implement. Since nobody stepped up do to this for more than a year I will close the issue for now. Feel free to re-open at any point if anybody is willing to implement it or fund the development.
